version: '3.9'

services:
  server:
    build:
      context: ./dockw/docsbackend
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: npm run start
    volumes:
      - ./dockw/docsbackend/:/usr/src/app
    ports:
      - "3001:3001"
  client:
    build:
      context: ./dockw
      dockerfile: dockerfile
    image: myapp-client
    container_name: myapp-node-client
    command: npm run start
    volumes:
      - ./dockw/:/usr/src/app
    ports:
      - "3000:3000"
  
volumes:
  pgdata: